### ISSUE TITLE
Diverse Bugs im Kommentarbereich

### ISSUE THREAD

**Issue by cqone** [Seglormeister/pr0gramm.com-by-Seglor#11]
Nabend,

habe gestern zum ersten Mal dein Script ausprobiert, aber irgendwie funktioniert es nicht so wie man sich das vorstellt. Im Kommentarbereich sind mir einige Anomalien bzw Fehler aufgefallen, die teils extrem nervig sind. Neustart, Neuinstallation, Cache leeren usw. haben nichts gebracht.

Bug 1:
http://abload.de/img/bugreport1f4eqo.png
Auf der linken Seite liegt ein Balken über alle Kommentare, was die Vote-Buttons, die Textbox für neue Kommentare und den "Abschicken"-Button teilweise verdeckt.

Bug 2:
http://abload.de/img/bugreport2c9ciz.png
Links neben den eingerückten Kommentaren ist die Opacity viel höher als der Hintergrund von dem Kommentar selbst. Kann man diese eventuell anpassen?

Bug 3:
http://abload.de/img/bugreport38ai6c.png
Die Scrollleiste wandert nicht ganz nach unten auch, wenn der letzte Kommentar angezeigt wird. (Siehe Bild: Auf dem Bild wird der letzte Kommentar ganz unten angezeigt, die Scrollbar befindet sich aber nicht ganz unten, sondern etwas weiter oben) Auch wenn z.B. nur wenige Kommentare geschrieben wurde und noch Platz ist, wird die Scrollbar bereits angezeigt und es kann nicht nach unten gescrollt werden.

Weitere Informationen:
- Browser: Google Chrome (Tampermonkey)
- Auflösung: 1920x1040px (Window); 1920x955px (Viewport)

**Comment by Seglormeister** [comment]
Sollten behoben sein.

Mfg
