### ISSUE TITLE
Benis wird nicht angezeigt

### ISSUE THREAD

**Issue by MAGICCC** [Seglormeister/pr0gramm.com-by-Seglor#12]
Hi,
benutze seit eben das Script und mir ist aufgefallen, dass der Benis nicht angezeigt wird
![77a](https://cloud.githubusercontent.com/assets/3279213/7667726/e03a0066-fc14-11e4-9a5d-d47bed56b83d.png)

**Comment by Toilettenpapier** [comment]
Bei mir ebenso nicht. Was ich dir aber empfehlen kann wäre Seglors Script in Kooperation mit diesem hier zu verwenden: http://pr0gramm.com/top/Mod%20it%20till%20it%20breaks/622568
