### ISSUE TITLE
Feature request: Bereits gesehen icon

### ISSUE THREAD

**Issue by 3rr0r404** [Seglormeister/pr0gramm.com-by-Seglor#6]
Ich vermisse bei dem Skript eine Anzeige, die mir zeigt, dass ich das aktuelle "geöffnete" Bild bereits gesehen habe. Jaja ich könnt mir ja merken was ich seit dem letzten Besuch auf der Seite gesehen habe, aber bei den derzeitigen Unmengen verliert man leicht den Überblick ;)

Mögliche Position: Ein Indikator neben dem Fav-Icon (class="pict vote-fav") oder etwas in im "Head" der Seite...

**Comment by Seglormeister** [comment]
Wird in der nächsten Version hinzugefügt.
