### ISSUE TITLE
FR: Dismiss current image on click

### ISSUE THREAD

**Issue by pr0nopoly** [Seglormeister/pr0gramm.com-by-Seglor#7]
Ich faends gut, wenn es wie im alten pr0gramm waere, dass das aktuell angezeigte Bild auch weg geht, wenn man in den Bereich um das Bild herum klickt. Also nicht nur direkt auf das Bild.

Ich mach das staedig aus alter Gewohnheit immer.

**Comment by Seglormeister** [comment]
Hm ja nur ich finde bei den ganzen Elementen unterm Bild, klickt man gerne mal daneben, wenn man mal upvoten will oder faven und wenn sich immer das Bild schließt, könnte es nerven. Im alten pr0gramm war es auch so, dass das Bild nur über einen Klick auf das Bild geschlosen wurde.

**Comment by pr0nopoly** [comment]
> Im alten pr0gramm war es auch so, dass das Bild nur ueber einen Klick auf das Bild geschlosen wurde.
Ich habe gerade noch mal im alten pr0 nachgeschaut:
https://web.archive.org/web/20130409211548/http://pr0gramm.com/#newest/*/90387/2013/02/hardcore-emo38
Es war anscheinend so, dass man auch ausserhalb des Bildes klicken konnte, da die Controls fuer Voting/Kommentare nicht im gleichen Container waren.

Es fehtl auch noch, dass man das Bild mit der Leertaste vergroessern/schliessen kann.

**Comment by Seglormeister** [comment]
Wenn man nun links/rechts neben das Bild klickt, schließt es sich.
Der Zoom per Leertaste geht nun auch. Verschieben lässt sich das Bild nach der Vergrößerung per Drag and Drop mit der Maus.
